<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- BASE LINK -->
    <!-- defined on the ground in the center of the robot-->
    <link name="base_link"></link>

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->
    <xacro:property name="chassis_radius" value="0.150"/>
    <xacro:property name="chassis_thickness" value="0.065"/>
    <xacro:property name="chassis_mass" value="0.500"/>
    <xacro:property name="chassis_color" value="white"/>

    <xacro:property name="chassis_offset_z" value="0.0425"/>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_thickness}"/>
            </geometry>
            <material name="${chassis_color}"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" radius="${chassis_radius}" length="${chassis_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- LEFT WHEEL LINK -->
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_thickness" value="0.015"/>
    <xacro:property name="wheel_mass" value="0.050"/>
    <xacro:property name="wheel_color" value="blue"/>

    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_separation" value="0.231"/>

    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left"/>
        <origin xyz="${wheel_offset_x} ${wheel_separation/2} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="wheel_left">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="${wheel_color}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- RIGHT WHEEL LINK -->
    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right"/>
        <origin xyz="${wheel_offset_x} ${-wheel_separation/2} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="wheel_right">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="${wheel_color}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEEL PLATE LINK -->
    <xacro:property name="caster_wheel_plate_radius" value="0.025"/>
    <xacro:property name="caster_wheel_plate_thickness" value="0.0001"/>
    <xacro:property name="caster_wheel_plate_mass" value="0.010"/>
    <xacro:property name="caster_wheel_plate_color" value="blue"/>

    <xacro:property name="caster_wheel_plate_offset_x" value="0.1"/>

    <joint name="caster_wheel_plate_joint" type="fixed">0
        <parent link="chassis"/>
        <child link="caster_wheel_plate"/>
        <origin xyz="${caster_wheel_plate_offset_x} 0 ${-chassis_thickness/2}"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="caster_wheel_plate">
        <visual>
            <origin xyz="0 0 ${-caster_wheel_plate_thickness/2}"/>
            <geometry>
                <cylinder radius="${caster_wheel_plate_radius}" length="${caster_wheel_plate_thickness}"/>
            </geometry>
            <material name="${caster_wheel_plate_color}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${caster_wheel_plate_radius}" length="${caster_wheel_plate_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_plate_mass}" radius="${caster_wheel_plate_radius}" length="${caster_wheel_plate_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEEL LINK -->
    <xacro:property name="caster_wheel_radius" value="0.010"/>
    <xacro:property name="caster_wheel_thickness" value="0.020"/>
    <xacro:property name="caster_wheel_mass" value="0.020"/>
    <xacro:property name="caster_wheel_color" value="blue"/>

    <xacro:property name="caster_wheel_offset_x" value="0.008"/>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="caster_wheel_plate"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 0" rpy="${pi/2}  0 0" />  
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
            <material name="${caster_wheel_color}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${caster_wheel_radius}" length="${caster_wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

</robot>