controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    range_sensor_broadcaster_left:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    range_sensor_broadcaster_front:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    range_sensor_broadcaster_right:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

diffbot_base_controller:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    
    wheel_separation: 0.231                     # [m] - for rotation
    wheel_radius: 0.032                         # [m] - for speed
    wheels_per_side: 1

    linear.x.has_velocity_limits: true
    #linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 0.10                 # [m/s] - v[m/s] = cmd_val[rad/s] * wheel_radius
    linear.x.min_velocity: -0.10                # [m/s]
    #linear.x.max_acceleration: 1.0              # [m/s²]

    angular.z.has_velocity_limits: true
    #angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 0.8658008658        # [rad/s] - cmd_val[rad/s] = v[mm/s] / ( wheel_seperation[mm] / 2 )
    angular.z.min_velocity: -0.8658008658       # [rad/s]
    #angular.z.max_acceleration: 1.0             # [rad/s²]
    #angular.z.min_acceleration: -1.0            # [rad/s²]

    use_stamped_vel: false

range_sensor_broadcaster_left:
  ros__parameters:
    sensor_name: "range_sensor_left"
    frame_id: "range_sensor_left"
    radiation_type: 1
    field_of_view: 0.1
    min_range: 0.10
    max_range: 7.0

range_sensor_broadcaster_front:
  ros__parameters:
    sensor_name: "range_sensor_front"
    frame_id: "range_sensor_front"
    radiation_type: 1
    field_of_view: 0.1
    min_range: 0.10
    max_range: 7.0

range_sensor_broadcaster_right:
  ros__parameters:
    sensor_name: "range_sensor_right"
    frame_id: "range_sensor_right"
    radiation_type: 1
    field_of_view: 0.1
    min_range: 0.10
    max_range: 7.0